# Generated by Django 3.2.9 on 2021-12-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_rename_miles_car_ride_kilometer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='milage',
            new_name='milage_city',
        ),
        migrations.AddField(
            model_name='car',
            name='milage_highway',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
