# Generated by Django 3.2.9 on 2021-12-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20211223_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='warrenty',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
